sensor_kit_base_link:
  camera6/camera_optical_link:
    x: 0.05
    y: -0.0175
    z: -0.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    fps: 30.0
    width: 1920
    height: 1280
    fov: 46.0
  camera7/camera_optical_link:
    x: 0.05
    y: 0.0175
    z: -0.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
    fps: 30.0
    width: 1920
    height: 1280
    fov: 85.0
  lidar_top_base_link:
    x: 6.2
    y: 0.0
    z: 2.8
    roll: 0.0
    pitch: 0.0
    yaw: 3.11151121805558
  lidar_left_base_link:
    x: 6.393484
    y: 1.185345
    z: 0.631320
    roll: -0.021033
    pitch: -0.005423
    yaw: 0.681538
  lidar_right_base_link:
    x: 6.364771
    y: -1.177943
    z: 0.659430
    roll: 0.005509
    pitch: 0.007263
    yaw: -0.793005
  lidar_left_rear_base_link:
    x: -2.8
    y: 1.185345
    z: 0.631320
    roll: 0.0
    pitch: 0.0
    yaw: 2.35619449019234
  lidar_right_rear_base_link:
    x: -2.8
    y: -1.177943
    z: 0.659430
    roll: 0.0
    pitch: 0.0
    yaw: -2.35619449019234
  gnss_link:
    x: 0.0
    y: 0.0
    z: 2.503
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 3.14159265359
    pitch: 0.017453292519943
    yaw: 0.0
  imu_link_xyz:
    x: 4.426
    y: -0.813
    z: -0.102
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  center_of_gravity_link:
    x: 1.835843373
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
