<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="sensor_kit_macro" params="parent x y z roll pitch yaw">
    <!--xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/-->
    <xacro:include filename="$(find velodyne_description)/urdf/VLP-32C.urdf.xacro"/>
    <xacro:include filename="$(find vls_description)/urdf/VLS-128.urdf.xacro"/>
    <xacro:include filename="$(find camera_description)/urdf/monocular_camera.xacro"/>
    <xacro:include filename="$(find imu_description)/urdf/imu.xacro"/>

    <xacro:arg name="gpu" default="false"/>
    <xacro:arg name="config_dir" default="$(find rainbow_sensor_kit_description)/config"/>

    <xacro:property name="sensor_kit_base_link" default="sensor_kit_base_link"/>

    <joint name="${sensor_kit_base_link}_joint" type="fixed">
      <origin rpy="${roll} ${pitch} ${yaw}" xyz="${x} ${y} ${z}"/>
      <parent link="${parent}"/>
      <child link="${sensor_kit_base_link}"/>
    </joint>
    <link name="${sensor_kit_base_link}">
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </link>

    <!-- sensor -->
    <xacro:property name="calibration" value="${xacro.load_yaml('$(arg config_dir)/sensor_kit_calibration.yaml')}"/>

    <!-- lidar -->
    <xacro:VLS-128 parent="sensor_kit_base_link" name="lidar_top" topic="/points_raw" hz="10" samples="220" gpu="$(arg gpu)">
      <origin
        xyz="${calibration['sensor_kit_base_link']['lidar_top_base_link']['x']}
             ${calibration['sensor_kit_base_link']['lidar_top_base_link']['y']}
             ${calibration['sensor_kit_base_link']['lidar_top_base_link']['z']}"
        rpy="${calibration['sensor_kit_base_link']['lidar_top_base_link']['roll']}
             ${calibration['sensor_kit_base_link']['lidar_top_base_link']['pitch']}
             ${calibration['sensor_kit_base_link']['lidar_top_base_link']['yaw']}"
      />
    </xacro:VLS-128>
    <xacro:VLP-32C parent="sensor_kit_base_link" name="lidar_left" topic="/points_raw" hz="10" samples="220" gpu="$(arg gpu)">
      <origin
        xyz="${calibration['sensor_kit_base_link']['lidar_left_base_link']['x']}
             ${calibration['sensor_kit_base_link']['lidar_left_base_link']['y']}
             ${calibration['sensor_kit_base_link']['lidar_left_base_link']['z']}"
        rpy="${calibration['sensor_kit_base_link']['lidar_left_base_link']['roll']}
             ${calibration['sensor_kit_base_link']['lidar_left_base_link']['pitch']}
             ${calibration['sensor_kit_base_link']['lidar_left_base_link']['yaw']}"
      />
    </xacro:VLP-32C>
    <xacro:VLP-32C parent="sensor_kit_base_link" name="lidar_right" topic="/points_raw" hz="10" samples="220" gpu="$(arg gpu)">
      <origin
        xyz="${calibration['sensor_kit_base_link']['lidar_right_base_link']['x']}
             ${calibration['sensor_kit_base_link']['lidar_right_base_link']['y']}
             ${calibration['sensor_kit_base_link']['lidar_right_base_link']['z']}"
        rpy="${calibration['sensor_kit_base_link']['lidar_right_base_link']['roll']}
             ${calibration['sensor_kit_base_link']['lidar_right_base_link']['pitch']}
             ${calibration['sensor_kit_base_link']['lidar_right_base_link']['yaw']}"
      />
    </xacro:VLP-32C>

    <!-- gnss -->
    <xacro:imu_macro
      name="gnss"
      parent="sensor_kit_base_link"
      namespace=""
      x="${calibration['sensor_kit_base_link']['gnss_link']['x']}"
      y="${calibration['sensor_kit_base_link']['gnss_link']['y']}"
      z="${calibration['sensor_kit_base_link']['gnss_link']['z']}"
      roll="${calibration['sensor_kit_base_link']['gnss_link']['roll']}"
      pitch="${calibration['sensor_kit_base_link']['gnss_link']['pitch']}"
      yaw="${calibration['sensor_kit_base_link']['gnss_link']['yaw']}"
      fps="100"
    />

    <!-- imu -->
    <xacro:imu_macro
      name="imu"
      parent="sensor_kit_base_link"
      namespace=""
      x="${calibration['sensor_kit_base_link']['imu_link']['x']}"
      y="${calibration['sensor_kit_base_link']['imu_link']['y']}"
      z="${calibration['sensor_kit_base_link']['imu_link']['z']}"
      roll="${calibration['sensor_kit_base_link']['imu_link']['roll']}"
      pitch="${calibration['sensor_kit_base_link']['imu_link']['pitch']}"
      yaw="${calibration['sensor_kit_base_link']['imu_link']['yaw']}"
      fps="100"
    />

    <!-- camera -->
    <xacro:monocular_camera_macro
      name="camera6"
      parent="sensor_kit_base_link"
      namespace="traffic_light_right_camera"
      x="${calibration['sensor_kit_base_link']['camera6/camera_optical_link']['x']}"
      y="${calibration['sensor_kit_base_link']['camera6/camera_optical_link']['y']}"
      z="${calibration['sensor_kit_base_link']['camera6/camera_optical_link']['z']}"
      roll="${calibration['sensor_kit_base_link']['camera6/camera_optical_link']['roll']}"
      pitch="${calibration['sensor_kit_base_link']['camera6/camera_optical_link']['pitch']}"
      yaw="${calibration['sensor_kit_base_link']['camera6/camera_optical_link']['yaw']}"
      fps="${calibration['sensor_kit_base_link']['camera6/camera_optical_link']['fps']}"
      width="${calibration['sensor_kit_base_link']['camera6/camera_optical_link']['width']}"
      height="${calibration['sensor_kit_base_link']['camera6/camera_optical_link']['height']}"
      fov="${calibration['sensor_kit_base_link']['camera6/camera_optical_link']['fov']}"
    />

    <xacro:monocular_camera_macro
      name="camera7"
      parent="sensor_kit_base_link"
      namespace="traffic_light_left_camera"
      x="${calibration['sensor_kit_base_link']['camera7/camera_optical_link']['x']}"
      y="${calibration['sensor_kit_base_link']['camera7/camera_optical_link']['y']}"
      z="${calibration['sensor_kit_base_link']['camera7/camera_optical_link']['z']}"
      roll="${calibration['sensor_kit_base_link']['camera7/camera_optical_link']['roll']}"
      pitch="${calibration['sensor_kit_base_link']['camera7/camera_optical_link']['pitch']}"
      yaw="${calibration['sensor_kit_base_link']['camera7/camera_optical_link']['yaw']}"
      fps="${calibration['sensor_kit_base_link']['camera7/camera_optical_link']['fps']}"
      width="${calibration['sensor_kit_base_link']['camera7/camera_optical_link']['width']}"
      height="${calibration['sensor_kit_base_link']['camera7/camera_optical_link']['height']}"
      fov="${calibration['sensor_kit_base_link']['camera7/camera_optical_link']['fov']}"
    />
  </xacro:macro>
</robot>
